### ISSUE TITLE
Add .vite directory in manifest.json path

### ISSUE THREAD

**Issue by leogallot** [MrBin99/django-vite#112]
Vite version 5 changed the path of the generated manifest.json file. It now generates it in a .vite directory.
https://vitejs.dev/guide/migration#manifest-files-are-now-generated-in-vite-directory-by-default

**Comment by petrprikryl** [comment]
Btw. using Vite's default (`.vite`) is not safe because Django's `collectstatic` command skips "hidden" files/folders.

https://github.com/django/django/blob/main/django/contrib/staticfiles/management/commands/collectstatic.py#L88

I would recommend to change https://github.com/MrBin99/django-vite/blob/66fce41b8eaaea97ff59e070c4ccce961dd6efb9/README.md#L73
to
```
  build: {
    manifest: "manifest.json",
```
to match the _django-vite_ default.

**Comment by noxan** [comment]
strongly agree with @petrprikryl. I just stumbled across this issue too, some remark to override the default for `mainfest` in the `vite.config.ts` would be very helpful :)
