### ISSUE TITLE
How I can using react components inside vite django.

### ISSUE THREAD

**Issue by abdalwhabSalahaldeen** [MrBin99/django-vite#13]
Thanks for this liberals.

How I can using react components inside vite django.??

**Comment by MrBin99** [comment]
Hi,
I'm not sure about your question, Django Vite do not care about what frontend framework you use or not.
You should start by looking at the ViteJS documentation, specificaly on existing templates [here](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
I'm sorry but I close this issue because it is not related to Django Vite directly.
