### ISSUE TITLE
How to deal with scss?

### ISSUE THREAD

**Issue by avadadevelopers** [MrBin99/django-vite#97]
How do you deal with scss?

**Comment by Niicck** [comment]
So that's more of vite question than a django-vite question. This library is just a wrapper to load vite assets into django templates.

But to answer your question, Vite only supports loading JavaScript files. But you can import css or scss into a JavaScript file and then load that file into your project. And then Vite will automatically create `<style>` tags to load in those css/scss assets.

Here's an example: https://github.com/Niicck/django-vite-multi-app-example/blob/main/examples/multi_app/django_app/django_app/vite_assets/css/main.css.js

And here's the vite documentation on using scss and friends: https://vitejs.dev/guide/features.html#css-pre-processors

**Comment by thijskramer** [comment]
^ What @Niicck said, this is more a Vite question.
